name: media-stack

include:
  - path: ./media-server-stack/docker-compose.yml
    project_directory: ./media-server-stack

  - path: ./media-download-stack/docker-compose.yml
    project_directory: ./media-download-stack

  - path: ./media-content-stack/docker-compose.yml
    project_directory: ./media-content-stack

networks:
  media_internal:
    driver: bridge
    name: media_internal
